version: '3.8'
services:
  parisjanitor-db:
    image:  mysql/mysql-server:5.6
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_DATABASE: parisjanitor
      MYSQL_USER: parisjanitor
      MYSQL_PASSWORD: parisjanitor
      MYSQL_ROOT_PASSWORD: parisjanitor
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: 3306
    networks:
      - parisjanitor-network
    restart: unless-stopped

  parisjanitor-api:
    depends_on:
      - parisjanitor-db
    image: jypast/parisjanitor-api:latest
    environment:
      PORT: 4000
      DB_SERVICE_NAME: parisjanitor-db
      DB_NAME: parisjanitor
      DB_USER: root
      DB_PASSWORD: parisjanitor
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - parisjanitor-network
    ports:
      - "4000:4000"
    restart: unless-stopped

  parisjanitor-front:
    image: jypast/parisjanitor-front:latest
    networks:
      - parisjanitor-network
    ports:
      - "5000:80"
    restart: unless-stopped

  parisjanitor-minio:
    image: minio/minio
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: parisjanitor
      MINIO_ROOT_PASSWORD: parisjanitor
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped

volumes:
  minio_storage: { }

networks:
  parisjanitor-network: